const BOARD_INCREASE_SIZE = 'BOARD_INCREASE_SIZE'
const LETTER_ADD = 'LETTER_ADD'
const LETTER_CLEAR = 'LETTER_CLEAR'
const LETTER_UPDATE = 'LETTER_UPDATE'
const POSSIBLE_WORDS_UPDATE = 'POSSIBLE_WORDS_UPDATE'
const WORD_MAKE = 'WORD_MAKE'

export default {
  BOARD_INCREASE_SIZE,
  LETTER_ADD,
  LETTER_CLEAR,
  LETTER_UPDATE,
  POSSIBLE_WORDS_UPDATE,
  WORD_MAKE,
}
